#!/bin/bash

SCRIPTPATH="$(realpath -s $0)"
SCRIPTDIR=$(dirname ${SCRIPTPATH})

source $SCRIPTDIR/colors

# Foreground
printf "${FG_DEFAULT} FG_DEFAULT ${ANSI_OFF}\n"
printf "${FG_BLACK} FG_BLACK ${ANSI_OFF}\n"
printf "${FG_RED} FG_RED ${ANSI_OFF}\n"
printf "${FG_GREEN} FG_GREEN ${ANSI_OFF}\n"
printf "${FG_YELLOW} FG_YELLOW ${ANSI_OFF}\n"
printf "${FG_BLUE} FG_BLUE ${ANSI_OFF}\n"
printf "${FG_MAGENTA} FG_MAGENTA ${ANSI_OFF}\n"
printf "${FG_CYAN} FG_CYAN ${ANSI_OFF}\n"
printf "${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
printf "${FG_LT_BLACK} FG_LT_BLACK ${ANSI_OFF}\n"
printf "${FG_LT_RED} FG_LT_RED ${ANSI_OFF}\n"
printf "${FG_LT_GREEN} FG_LT_GREEN ${ANSI_OFF}\n"
printf "${FG_LT_YELLOW} FG_LT_YELLOW ${ANSI_OFF}\n"
printf "${FG_LT_BLUE} FG_LT_BLUE ${ANSI_OFF}\n"
printf "${FG_LT_MAGENTA} FG_LT_MAGENTA ${ANSI_OFF}\n"
printf "${FG_LT_CYAN} FG_LT_CYAN ${ANSI_OFF}\n"
printf "${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
echo ""

# Bold
printf "${BOLD}${FG_DEFAULT} FG_DEFAULT ${ANSI_OFF}\n"
printf "${BOLD}${FG_BLACK} FG_BLACK ${ANSI_OFF}\n"
printf "${BOLD}${FG_RED} FG_RED ${ANSI_OFF}\n"
printf "${BOLD}${FG_GREEN} FG_GREEN ${ANSI_OFF}\n"
printf "${BOLD}${FG_YELLOW} FG_YELLOW ${ANSI_OFF}\n"
printf "${BOLD}${FG_BLUE} FG_BLUE ${ANSI_OFF}\n"
printf "${BOLD}${FG_MAGENTA} FG_MAGENTA ${ANSI_OFF}\n"
printf "${BOLD}${FG_CYAN} FG_CYAN ${ANSI_OFF}\n"
printf "${BOLD}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
printf "${BOLD}${FG_LT_BLACK} FG_LT_BLACK ${ANSI_OFF}\n"
printf "${BOLD}${FG_LT_RED} FG_LT_RED ${ANSI_OFF}\n"
printf "${BOLD}${FG_LT_GREEN} FG_LT_GREEN ${ANSI_OFF}\n"
printf "${BOLD}${FG_LT_YELLOW} FG_LT_YELLOW ${ANSI_OFF}\n"
printf "${BOLD}${FG_LT_BLUE} FG_LT_BLUE ${ANSI_OFF}\n"
printf "${BOLD}${FG_LT_MAGENTA} FG_LT_MAGENTA ${ANSI_OFF}\n"
printf "${BOLD}${FG_LT_CYAN} FG_LT_CYAN ${ANSI_OFF}\n"
printf "${BOLD}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
echo ""

# Dim
printf "${DIM}${FG_DEFAULT} FG_DEFAULT ${ANSI_OFF}\n"
printf "${DIM}${FG_BLACK} FG_BLACK ${ANSI_OFF}\n"
printf "${DIM}${FG_RED} FG_RED ${ANSI_OFF}\n"
printf "${DIM}${FG_GREEN} FG_GREEN ${ANSI_OFF}\n"
printf "${DIM}${FG_YELLOW} FG_YELLOW ${ANSI_OFF}\n"
printf "${DIM}${FG_BLUE} FG_BLUE ${ANSI_OFF}\n"
printf "${DIM}${FG_MAGENTA} FG_MAGENTA ${ANSI_OFF}\n"
printf "${DIM}${FG_CYAN} FG_CYAN ${ANSI_OFF}\n"
printf "${DIM}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
printf "${DIM}${FG_LT_BLACK} FG_LT_BLACK ${ANSI_OFF}\n"
printf "${DIM}${FG_LT_RED} FG_LT_RED ${ANSI_OFF}\n"
printf "${DIM}${FG_LT_GREEN} FG_LT_GREEN ${ANSI_OFF}\n"
printf "${DIM}${FG_LT_YELLOW} FG_LT_YELLOW ${ANSI_OFF}\n"
printf "${DIM}${FG_LT_BLUE} FG_LT_BLUE ${ANSI_OFF}\n"
printf "${DIM}${FG_LT_MAGENTA} FG_LT_MAGENTA ${ANSI_OFF}\n"
printf "${DIM}${FG_LT_CYAN} FG_LT_CYAN ${ANSI_OFF}\n"
printf "${DIM}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
echo ""

# Underline
printf "${UNDERLINE}${FG_DEFAULT} FG_DEFAULT ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_BLACK} FG_BLACK ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_RED} FG_RED ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_GREEN} FG_GREEN ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_YELLOW} FG_YELLOW ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_BLUE} FG_BLUE ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_MAGENTA} FG_MAGENTA ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_CYAN} FG_CYAN ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_LT_BLACK} FG_LT_BLACK ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_LT_RED} FG_LT_RED ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_LT_GREEN} FG_LT_GREEN ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_LT_YELLOW} FG_LT_YELLOW ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_LT_BLUE} FG_LT_BLUE ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_LT_MAGENTA} FG_LT_MAGENTA ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_LT_CYAN} FG_LT_CYAN ${ANSI_OFF}\n"
printf "${UNDERLINE}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
echo ""

# Blink
printf "${BLINK}${FG_DEFAULT} FG_DEFAULT ${ANSI_OFF}\n"
printf "${BLINK}${FG_BLACK} FG_BLACK ${ANSI_OFF}\n"
printf "${BLINK}${FG_RED} FG_RED ${ANSI_OFF}\n"
printf "${BLINK}${FG_GREEN} FG_GREEN ${ANSI_OFF}\n"
printf "${BLINK}${FG_YELLOW} FG_YELLOW ${ANSI_OFF}\n"
printf "${BLINK}${FG_BLUE} FG_BLUE ${ANSI_OFF}\n"
printf "${BLINK}${FG_MAGENTA} FG_MAGENTA ${ANSI_OFF}\n"
printf "${BLINK}${FG_CYAN} FG_CYAN ${ANSI_OFF}\n"
printf "${BLINK}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
printf "${BLINK}${FG_LT_BLACK} FG_LT_BLACK ${ANSI_OFF}\n"
printf "${BLINK}${FG_LT_RED} FG_LT_RED ${ANSI_OFF}\n"
printf "${BLINK}${FG_LT_GREEN} FG_LT_GREEN ${ANSI_OFF}\n"
printf "${BLINK}${FG_LT_YELLOW} FG_LT_YELLOW ${ANSI_OFF}\n"
printf "${BLINK}${FG_LT_BLUE} FG_LT_BLUE ${ANSI_OFF}\n"
printf "${BLINK}${FG_LT_MAGENTA} FG_LT_MAGENTA ${ANSI_OFF}\n"
printf "${BLINK}${FG_LT_CYAN} FG_LT_CYAN ${ANSI_OFF}\n"
printf "${BLINK}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
echo ""

# Invert
printf "${INVERT}${FG_DEFAULT} FG_DEFAULT ${ANSI_OFF}\n"
printf "${INVERT}${FG_BLACK} FG_BLACK ${ANSI_OFF}\n"
printf "${INVERT}${FG_RED} FG_RED ${ANSI_OFF}\n"
printf "${INVERT}${FG_GREEN} FG_GREEN ${ANSI_OFF}\n"
printf "${INVERT}${FG_YELLOW} FG_YELLOW ${ANSI_OFF}\n"
printf "${INVERT}${FG_BLUE} FG_BLUE ${ANSI_OFF}\n"
printf "${INVERT}${FG_MAGENTA} FG_MAGENTA ${ANSI_OFF}\n"
printf "${INVERT}${FG_CYAN} FG_CYAN ${ANSI_OFF}\n"
printf "${INVERT}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
printf "${INVERT}${FG_LT_BLACK} FG_LT_BLACK ${ANSI_OFF}\n"
printf "${INVERT}${FG_LT_RED} FG_LT_RED ${ANSI_OFF}\n"
printf "${INVERT}${FG_LT_GREEN} FG_LT_GREEN ${ANSI_OFF}\n"
printf "${INVERT}${FG_LT_YELLOW} FG_LT_YELLOW ${ANSI_OFF}\n"
printf "${INVERT}${FG_LT_BLUE} FG_LT_BLUE ${ANSI_OFF}\n"
printf "${INVERT}${FG_LT_MAGENTA} FG_LT_MAGENTA ${ANSI_OFF}\n"
printf "${INVERT}${FG_LT_CYAN} FG_LT_CYAN ${ANSI_OFF}\n"
printf "${INVERT}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
echo ""

# Strikethrough
printf "${STRIKE}${FG_DEFAULT} FG_DEFAULT ${ANSI_OFF}\n"
printf "${STRIKE}${FG_BLACK} FG_BLACK ${ANSI_OFF}\n"
printf "${STRIKE}${FG_RED} FG_RED ${ANSI_OFF}\n"
printf "${STRIKE}${FG_GREEN} FG_GREEN ${ANSI_OFF}\n"
printf "${STRIKE}${FG_YELLOW} FG_YELLOW ${ANSI_OFF}\n"
printf "${STRIKE}${FG_BLUE} FG_BLUE ${ANSI_OFF}\n"
printf "${STRIKE}${FG_MAGENTA} FG_MAGENTA ${ANSI_OFF}\n"
printf "${STRIKE}${FG_CYAN} FG_CYAN ${ANSI_OFF}\n"
printf "${STRIKE}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
printf "${STRIKE}${FG_LT_BLACK} FG_LT_BLACK ${ANSI_OFF}\n"
printf "${STRIKE}${FG_LT_RED} FG_LT_RED ${ANSI_OFF}\n"
printf "${STRIKE}${FG_LT_GREEN} FG_LT_GREEN ${ANSI_OFF}\n"
printf "${STRIKE}${FG_LT_YELLOW} FG_LT_YELLOW ${ANSI_OFF}\n"
printf "${STRIKE}${FG_LT_BLUE} FG_LT_BLUE ${ANSI_OFF}\n"
printf "${STRIKE}${FG_LT_MAGENTA} FG_LT_MAGENTA ${ANSI_OFF}\n"
printf "${STRIKE}${FG_LT_CYAN} FG_LT_CYAN ${ANSI_OFF}\n"
printf "${STRIKE}${FG_WHITE} FG_WHITE ${ANSI_OFF}\n"
echo ""

# Background
printf "${BG_DEFAULT} BG_DEFAULT ${NC}\n"
printf "${BG_BLACK} BG_BLACK ${NC}\n"
printf "${BG_RED} BG_RED ${NC}\n"
printf "${BG_GREEN} BG_GREEN ${NC}\n"
printf "${BG_YELLOW} BG_YELLOW ${NC}\n"
printf "${BG_BLUE} BG_BLUE ${NC}\n"
printf "${BG_MAGENTA} BG_MAGENTA ${NC}\n"
printf "${BG_CYAN} BG_CYAN ${NC}\n"
printf "${BG_WHITE} BG_WHITE ${NC}\n"
printf "${BG_LT_BLACK} BG_LT_BLACK ${NC}\n"
printf "${BG_LT_RED} BG_LT_RED ${NC}\n"
printf "${BG_LT_GREEN} BG_LT_GREEN ${NC}\n"
printf "${BG_LT_YELLOW} BG_LT_YELLOW ${NC}\n"
printf "${BG_LT_BLUE} BG_LT_BLUE ${NC}\n"
printf "${BG_LT_MAGENTA} BG_LT_MAGENTA ${NC}\n"
printf "${BG_LT_CYAN} BG_LT_CYAN ${NC}\n"
printf "${BG_LT_WHITE} BG_LT_WHITE ${NC}\n"
echo ""

