#!/bin/bash

################################################################################
# Predefined ANSI color codes for colorful output strings.
#
# WARNING: This is not an executable script. This script is meant to be used as
# a utility by sourcing this script for efficient bash script writing.
#
################################################################################
# Resources:
#   https://en.wikipedia.org/wiki/ANSI_escape_code
#   https://misc.flogisoft.com/bash/tip_colors_and_formatting#links
################################################################################
# Author : Mark Lucernas <https://github.com/marklcrns>
# Date   : 2020-08-13
################################################################################

# Prevent from being executed directly in the terminal
if [ ${0##*/} == ${BASH_SOURCE[0]##*/} ]; then
  echo "WARNING:"
  echo "$(realpath -s $0) is not meant to be executed directly!"
  echo "Use this script only by sourcing it."
  echo
  exit 1
fi


# Set ANSI
BOLD="\e[1m"
DIM="\e[2m"
UNDERLINE="\e[4m"
BLINK="\e[5m"   # Works in tty and XTerm emulators
INVERT="\e[7m"
HIDE="\e[8m"
STRIKE="\e[9m"

# Unset ANSI
ANSI_OFF="\e[0m"    # Unset all attributes
BOLD_OFF="\e[21m"
DIM_OFF="\e[22m"
UNDERLINE_OFF="\e[24m"
BLINK_OFF="\e[25m"
INVERT_OFF="\e[27m"
HIDE_OFF="\e[28m"
STRIKE_OFF="\e[29m"

# Foreground
FG_DEFAULT="\e[39m"
FG_BLACK="\e[30m"
FG_RED="\e[31m"
FG_GREEN="\e[32m"
FG_YELLOW="\e[33m"
FG_BLUE="\e[34m"
FG_MAGENTA="\e[35m"
FG_CYAN="\e[36m"
FG_WHITE="\e[37m"
FG_LT_BLACK="\e[90m"
FG_LT_RED="\e[91m"
FG_LT_GREEN="\e[92m"
FG_LT_YELLOW="\e[93m"
FG_LT_BLUE="\e[94m"
FG_LT_MAGENTA="\e[95m"
FG_LT_CYAN="\e[96m"
FG_LT_WHITE="\e[97m"

# Background
BG_DEFAULT="\e[49m"
BG_BLACK="\e[40m"
BG_RED="\e[41m"
BG_GREEN="\e[42m"
BG_YELLOW="\e[43m"
BG_BLUE="\e[44m"
BG_MAGENTA="\e[45m"
BG_CYAN="\e[46m"
BG_WHITE="\e[47m"
BG_LT_BLACK="\e[100m"
BG_LT_RED="\e[101m"
BG_LT_GREEN="\e[102m"
BG_LT_YELLOW="\e[103m"
BG_LT_BLUE="\e[104m"
BG_LT_MAGENTA="\e[105m"
BG_LT_CYAN="\e[106m"
BG_LT_WHITE="\e[107m"
BG_EX="\e[K"    # Expand any background color horizontally


# Old support
NC="\e[0m"
BO_NC="\e[21m"
DEFAULT="\e[39m"
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
WHITE="\e[37m"
