#!/bin/bash

# Watch $SOURCE_DIR for file creation or files moved into $SOURCE_DIR ending
# with $FILE_EXT to automatically move all files containing $FILE_EXT into
# current directory.
#
# Additionally, change file permission to chmod 644 after moving.

set -e

if [[ -d "${1:-}" ]]; then
  SOURCE_DIR="${1}"
  shift 1
else
  echo -e "No directory specified"
  exit 1
fi

declare -a FILE_EXT=("${@:-*}")

SOURCE_DIR=$(echo "${SOURCE_DIR}" | sed 's,/*$,,')

echo -e "Now watching ${SOURCE_DIR} for ${FILE_EXT[@]} asset files..."

if [[ "$(grep -i microsoft /proc/version)" ]]; then
  # Manual file watching for WSL since `inotifywait` cannot detect Windows 10
  # file creation
  while true; do
    for file_ext in ${FILE_EXT[@]}; do
      if [[ -n "$(ls ${SOURCE_DIR}/*.${file_ext} 2>/dev/null)" ]]; then
        mv -v ${SOURCE_DIR}/*.${file_ext} . && chmod 644 *.${file_ext}
      fi
    done
    sleep 1
  done
else
  # Ref: https://unix.stackexchange.com/a/323919
  inotifywait -m ${SOURCE_DIR} -e create,moved_to,modify |
    while read path action file; do
      for file_ext in ${FILE_EXT[@]}; do
        if [[ "${file}" =~ .*${file_ext}$ ]]; then
          mv -v ${file_ext}/*.${file_ext} . && chmod 644 *.${file_ext}
        fi
      done
    done
fi

